name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      test_pipaudit: true
      pipaudit_ignored: "GHSA-r9hx-vwmv-q579 PYSEC-2022-43012 GHSA-j8r2-6x86-q33q"