name: Run License Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master