name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_gui_plugin_shell_companion/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_gui_plugin_shell_companion/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install .
      - name: Install test dependencies
        run: |
          pip install -r test/requirements.txt
      - name: Run unittests
        run: |
          pytest --cov=ovos_gui_plugin_shell_companion --cov-report xml test/unittests
          # NOTE: additional pytest invocations should also add the --cov-append flag
          #       or they will overwrite previous invocations' coverage reports
          #       (for an example, see OVOS Skill Manager's workflow)
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v2
